server:
  port: 9091

spring:
  application:
    name: BlogStackCommonsService

  datasource:
    url: jdbc:postgresql://ec2-3-110-224-124.ap-south-1.compute.amazonaws.com:5432/blogstackcommons
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: blogstack12@gmail.com
    password: vlmferrarejnclku
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
commons-service-version: v1.0
cloud:
  aws:
    credentials:
      access-key: AKIAXFYS2UY4HECCOTYR
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    profile: blogstackprofilephoto
    blog: blogstack-upload-blog-image

