server:
  port: 9091

spring:
  application:
    name: BlogStackCommonsService

  datasource:
    url: jdbc:postgresql://localhost:5432/BlogStackMaster
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

commons-service-version: v1.0

cloud:
  aws:
    credentials:
      access-key: AKIAXFYS2UY4HECCOTYR
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    profile: blogstackprofilephoto
    blog: blogstack-upload-blog-image
